name:                testdb
version:             0.1.0.0
github:              "screwyprof/testdb"
license:             BSD3
author:              "Happygopher"
maintainer:          "max@happygopher.nl"
copyright:           "2020 Happygopher"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/screwyprof/testdb#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - postgresql-simple
    - bytestring
    - safe-exceptions

executables:
  testdb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - testdb

tests:
  testdb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - testdb
    - bytestring
    - hspec
    - postgresql-simple
